### ISSUE TITLE
Suggestion: change folder result

### ISSUE THREAD

**Issue by Sebio1980** [Fr75s/bigscraperqt#5]
Hello,
in the interface, I select the location of my games for a system. 
Example: "/recalbox/share/roms/snes"
But the scrape result doesn't go in there, it goes in "/recalbox/share/system/.local/share/bigscraper-qt/"
It would be better for systems to have the following tree as a result. 
Example: 
"/recalbox/share/roms/snes/media/video/f-zero.mp4"
"/recalbox/share/roms/snes/media/screenshot/f-zero.png"
"/recalbox/share/roms/snes/media/fanart/f-zero.png"
"/recalbox/share/roms/snes/media/box3d/f-zero.png"
"/recalbox/share/roms/snes/media/box2d/f-zero.png"
etc...
"/recalbox/share/roms/snes/media/video/Mario kart.mp4"
"/recalbox/share/roms/snes/media/screenshot/Mario kart.png"
"/recalbox/share/roms/snes/media/fanart/Mario kart.png"
"/recalbox/share/roms/snes/media/box3d/Mario kart.png"
"/recalbox/share/roms/snes/media/box2d/Mario kart.png"
etc...
Thank you for your help.

**Comment by Fr75s** [comment]
I feel like this is a misunderstanding, as this is exactly what exporting does.

In the application, alongside the option to scrape there is the option to export data under the export tab. Here, data is copied and converted to the format you have listed here.

What's stored in `/recalbox/share/system/.local/share/bigscraper-qt` is the *internal* data stored by bigscraper-qt. Exporting is a separate step as it may be done in a location other than where your games are. This is also done because you may want to export to EmulationStation versus Pegasus, or change some options beforehand.

This feature is already in bigscraper-qt, in the export tab. If this is what you want, then it's already in the program. If I am misunderstanding this and you want to have the raw, un-exported data stored elsewhere (json files and media), let me know.

![image](https://user-images.githubusercontent.com/98292839/196009151-ad60183a-a9b1-4bb9-87f1-0967d5d16162.png)

**Comment by Sebio1980** [comment]
Sorry for my English, I'm French.

You didn't misunderstand. It is that the display in our OS is not successful here is an image.
<a href="https://zupimages.net/viewer.php?id=22/41/shxd.jpg"><img src="https://zupimages.net/up/22/41/shxd.jpg" alt="" /></a>
<a href="https://zupimages.net/viewer.php?id=22/41/tmm2.jpg"><img src="https://zupimages.net/up/22/41/tmm2.jpg" alt="" /></a>

In our OS based on recalbox(emulastation but with the pegasus-frontend) we use "gamelist.xml and not metadata.pegasus.txt", we are currently running your software to test it. But the goal and with your agreement and your help will be to integrate your software natively in our OS to allow users to scrap their games.
And therefore to have the result directly in the folder where the roms are located by systems. "/recalbox/share/roms/{system}"

I just tested the export and I have an issue that I open with the ticket https://github.com/Fr75s/bigscraperqt/issues/8

**Comment by Fr75s** [comment]
Since exporting with EmulationStation (what I assume you want to do) was fixed in bf49fd9 (refer to #8), data should be returned in the format you listed. I'll wait to see if you have successfully exported with EmulationStation before closing this.
