### ISSUE TITLE
Suggestion: hide password screenscraper

### ISSUE THREAD

**Issue by Sebio1980** [Fr75s/bigscraperqt#6]
Hello,

In your software for account screenscraper, it would be good to hide the password in the options and log part.

Thank you

**Comment by Fr75s** [comment]
This issue should be fixed in bf49fd9. Passwords are hidden in both the application (the options menu now displays dots) and in the logs (no URLs are shown, hiding passwords).

Note that the side effect to this is that using backspace on the password field deletes the entire password. Probably something wrong with Qt, I'm unsure why it's happening, but it's only an issue if you are typing in the password manually.
