### ISSUE TITLE
Suggestions: add other system

### ISSUE THREAD

**Issue by Sebio1980** [Fr75s/bigscraperqt#7]
Hello,

In your software i don't see : 
- MAME
- ATOMISWAVE
- SEGA MODEL1
- SEGA MODEL2
- SEGA MODEL3
- SEGA CHIHIRO
- FBNEO
- NEOGEO

Thank you for add this.

**Comment by Fr75s** [comment]
This issue was at least partially solved in bf49fd9. The following systems have been added as a part of ScreenScraper scraping:
- MAME
- Sega Model II
- Sega Model III
- Neo Geo
- Atomiswave

Sadly, I couldn't find any listing on ScreenScraper (neither on the website or the API) for Sega Model I, Sega Chihiro and Final Burn Neo, so these weren't added.

**Comment by Sebio1980** [comment]
hello for the FBNEO by 
[screenscraper fbneo into mame](https://screenscraper.fr/systemesinfos.php?plateforme=1&alpha=M&numpage=0)
MAME :
Name Recalbox : arcade,mame,fba,fba_libretro,fbneo 
Name Retropie : arcade,fba,mame-advmame,mame-libretro,mame-mame4all,mame,mess
Name Launchbox : arcade 
Name Hyperspin : Final Burn Alpha,HBMAME,MAME,MiSFiT MAME 
Name TheGamesDB : Arcade

finaly it's the same MAME :)
